---
# @tag docker-container-prereq-all:description: Ensure all pre-requisites are installed
# @tag docker-container-prereq-wgaccess:description: Ensure all pre-requisites for wgaccess are installed
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/prereq.yml"
  tags:
    - docker-container-prereq-all
    - docker-container-prereq-wgaccess

# @tag docker-container-restore-all:description: Run restic restore for all restic enabled containers.
# @tag docker-container-restore-wgaccess:description: Run restic restore for wgaccess if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/restore.yml"
  tags:
    - never
    - docker-container-restore-all
    - docker-container-restore-wgaccess
  when:
    - docker_container_wgaccess_restic_enable

# @tag docker-container-setup-all:description: Run setup task for all containers.
# @tag docker-container-setup-wgaccess:description: Run setup task for wgaccess.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-wgaccess
    - docker-container-restore-all
    - docker-container-restore-wgaccess

# @tag docker-container-backup-init-all:description: Run init backup task for all container.
# @tag docker-container-backup-init-wgaccess:description: Run init backup task for wgaccess if restic is enabled.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_init.yml"
  tags:
    - docker-container-setup-all
    - docker-container-setup-wgaccess
    - docker-container-backup-init-all
    - docker-container-backup-init-wgaccess
  when:
    - docker_container_wgaccess_restic_enable

# @tag docker-container-remove-all:description: Remove all containers.
# @tag docker-container-remove-wgaccess:description: Remove wgaccess.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/remove.yml"
  tags:
    - never
    - docker-container-remove-all
    - docker-container-remove-wgaccess
    - docker-container-purge-all
    - docker-container-purge-wgaccess

# @tag docker-container-purge-all:description: Remove all containers and delete volume mounts.
# @tag docker-container-purge-wgaccess:description: Remove wgaccess and delete volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/purge.yml"
  tags:
    - never
    - docker-container-purge-all
    - docker-container-purge-wgaccess

# @tag docker-container-backup-all:description: Backup all containers' volume mounts.
# @tag docker-container-backup-wgaccess:description: Backup wgaccess volume mounts.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup.yml"
  tags:
    - never
    - docker-container-backup-all
    - docker-container-backup-wgaccess
  when:
    - docker_container_wgaccess_restic_enable

# @tag docker-container-backup-list-all:description: List all containers' backups.
# @tag docker-container-backup-list-wgaccess:description: List wgaccess backups.
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/backup_list.yml"
  tags:
    - never
    - docker-container-backup-list-all
    - docker-container-backup-list-wgaccess
  when:
    - docker_container_wgaccess_restic_enable
